development:
  environment: "sandbox"
  username: "signupforuseratsandboxpaypal"
  password: "signupforuseratsandboxpaypal"
  signature: "signupforuseratsandboxpaypal"
  application_id: "APP-TEST"
  ssl_cert_file:

test:
  environment: "sandbox"
  username: "signupforuseratsandboxpaypal"
  password: "signupforuseratsandboxpaypal"
  signature: "signupforuseratsandboxpaypal"
  application_id: "APP-TEST"
  ssl_cert_file:

production:
  environment: "production"
  username: "my_production_username"
  password: "my_production_password"
  signature: "my_production_signature"
  application_id: "my_production_app_id"
  ssl_cert_file:

with_erb_tags:
  environment: "sandbox"
  username: <%= ENV['paypal.username'] %>
  password: <%= ENV['paypal.password'] %>
  signature: "signupforuseratsandboxpaypal"
  application_id: "APP-TEST"
  ssl_cert_file:
